MXF parsing: terminate strings on the first null character
Netflix/photon pull request #373
Opened 2024-06-26 14:18 UTC by thomasheritage

Per SMPTE ST 377-1:2019, a "zero value" can be used to terminate a string.

So, discard any data after the first null character found (if any).

This has the same effect as the implementation for strings in regxmllib at: https://github.com/sandflow/regxmllib/blob/b47b0cdbd6dbf51cae4fb14c3a6a827eb3e0e2cc/src/main/java/com/sandflow/smpte/regxml/FragmentBuilder.java#L902

Note that regxmllib also uses the same `readCharacters` method for MXF properties with a Type of Type Kind "Character", and allows values of this Type to contain the null character.
Photon does not support such "Character" Types (and indeed none have ever been used in MXF according to the SMPTE Metadata Registers). So, no consideration is given to these Types in this patch.

Closes #372

2024-10-15 03:10 UTC, palemieux commented on src/main/java/com/netflix/imflibrary/MXFPropertyPopulator.java
> +        return new String(byteArray, charset).split("\u0000", 2)[0];
I am not in love with the `split`.

What about?

```
         String s = String(byteArray, charset);

         int i = s.indexOf('\u0000');

        if (i== -1) {
            return s;
        }

        return s.substring(0, i);
```

2024-10-15 03:11 UTC, palemieux requested changes
A test case should ideally be added.

2024-11-08 19:25 UTC, thomasheritage commented
I've updated the branch to amend the code and add a test (with a small MXF file containing Header Metadata with strings that are null terminated: prior to the code fix an error was given by Photon for this file per https://github.com/Netflix/photon/issues/372#issue-2375490069 )

2024-11-08 21:39 UTC, palemieux approved these changes

2024-11-20 18:05 UTC, merged