Add App2E HTJ2K constraints validation
Netflix/photon pull request #375
Opened 2024-08-15 18:36 UTC by fschleich

(Branched off of [PR #368](https://github.com/Netflix/photon/pull/368) to work around GitHub permission issues.)

Closes #370 

Validate the CPL essence descriptors against the APP2.HT.REV and APP2.HT.IRV constraint sets specified in [ST 2067-21, Annex I](https://pub.smpte.org/doc/st2067-21/20221124-pub/).

2024-08-15 19:16 UTC, danielhdz13-netflix approved these changes

2024-08-20 20:13 UTC, palemieux requested changes

2024-08-20 20:13 UTC, palemieux commented on src/main/java/com/netflix/imflibrary/st2067_2/Application2E2021.java
> +            isValid = true;
Remove since isValid is true by default and you would not want to overwrite a false value.

2024-08-20 20:13 UTC, palemieux commented on src/main/java/com/netflix/imflibrary/st2067_2/Application2E2021.java
> +                    "APP2.HT: Parameter B has exceeded its limit to an extend that decoder issues are to be expected");
`                    "APP2.HT: Parameter B has exceeded its limit to an extent that decoder issues are to be expected");`

2024-08-20 20:13 UTC, palemieux commented on src/main/java/com/netflix/imflibrary/st2067_2/Application2E2021.java
> +        if (codestreamB > 24) {
I would be inclined to use the max value allowed in Annex I, i.e., 21.

2024-08-20 22:27 UTC, merged